### ISSUE TITLE
[suggestion] RSS feed

### ISSUE THREAD

**Issue by sbdchd** [aviatesk/aviatesk.github.io#1]
The Franklin.jl docs outline RSS support, which requires a bit more config: https://franklinjl.org/syntax/page-variables/#rss

and the Julia blog uses the following config for their RSS feed: https://github.com/JuliaLang/www.julialang.org/blob/eef78385920ed72ccebc6fb0f85f6212ce5226f0/config.md

Readers can save then save RSS feeds in a reader and get notifications for new posts

**Comment by aviatesk** [comment]
Thanks for the suggestion. I've not used RSS, but I'm happy to support that. Let you know once I've setup it (maybe I'll do this weekend).

**Comment by aviatesk** [comment]
Okay, I've setup RSS feed [here](https://aviatesk.github.io/feed.xml).
Since I'm not using it I'd appreciate if you try to see if it works. Anyway thanks for your suggestion !

**Comment by sbdchd** [comment]
Yup it's working, thanks!
