### ISSUE TITLE
Please tell me the origin of the name "soteria"

### ISSUE THREAD

**Issue by NoBuHiToH** [aviatesk/aviatesk.github.io#3]
## Overview
まじで困ってるので、issue切りましたｗ (twitterでもいいかなと思ったけど、こっちのが面白そうだったので）
久しぶりです。芳賀です。
soteriaが無事に本番システムに導入され規模も大きくなってきたのでsoteriaのiconかlogoを作ろうと思ったのだけど、名前の由来を思い出せず困ってます。

## Purpose
名前の由来を理解し、無事にiconやlogoが作れる状態になること。

## Task
- [ ] 名前の由来を教えてあげる.

**Comment by aviatesk** [comment]
芳賀さんお久しぶりです！ 何すかこの最高すぎるissue笑笑
Soteria そんなに成長したんですね... ちょー嬉しいですありがとうございます❤️

"Soteria" の名前は、ギリシャ神話の [「安全性・危害からの解放」の神様](https://en.wikipedia.org/wiki/Soteria_(mythology)) の名前をそのままもらいました！
システムの目的にピッタシだなーって思って。
神話だと女神様なんですが個人的には特に性別は考えてなくて、シンプルでソリッドなイメージを持ってます:)
なので盾とかそういうアイコンが似合いそう？な気がしてます。

P.S. twitterやってるならDMください！芳賀さんフォローしたい笑

**Comment by NoBuHiToH** [comment]
ありがとう！

> シンプルでソリッドなイメージを持ってます:) なので盾とかそういうアイコンが似合いそう？な気がしてます。  

icon作るときに参考にします。
そして残念ながらtwitterは完全にROMなの....、また話したいネタあったらひっそりとissue切りますｗ

P.S. もうちょっと暖かくなったらまた飲みにでもいきましょ。

**Comment by aviatesk** [comment]
> P.S. もうちょっと暖かくなったらまた飲みにでもいきましょ。

ぜひぜひ！！！
それならRのスラックでお声かけさせていただきますね笑
